# netlify.toml

[build]
  publish = "/"
  command = ""  # no build step for plain HTML/CSS/JS

# -------------------------------------------------
# All branch deploys (dev, staging, feature branches)
[context.branch-deploy]
  [[headers]]
    for = "/*"
    [headers.values]
    Authorization = "Basic ${DEV_AUTH}"

  [[headers]]
    for = "/*"
    [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# -------------------------------------------------
# Deploy previews (PRs)
[context.deploy-preview]
  [[headers]]
    for = "/*"
    [headers.values]
    Authorization = "Basic ${DEV_AUTH}"

  [[headers]]
    for = "/*"
    [headers.values]
    X-Robots-Tag = "noindex, nofollow"

# -------------------------------------------------
# Production / main branch
[context.production]
  [[headers]]
    for = "/*"
    [headers.values]
    X-Robots-Tag = "index, follow"
